#!/usr/bin/env python3
"""Grade a hand-picked sequence of real frames into a cinematic product reel.

Hand-coded 3D can't look photoreal — real photography already is. These are the
strongest shots of the purple Sur-Ron, graded to a common look so they crossfade
as one continuous piece: near-monochrome, crushed blacks, violet lift in the
shadows, heavy vignette so the background falls away and the bike carries.
"""
import os, math
import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "frames")
OUT = os.path.join(ROOT, "assets", "hero")

# Ordered as a reel: reveal → detail → stance → action.
SHOTS = [
    ("S86L3rvOvOE_oar3.jpg",       "SIDE PROFILE",   "Sur-Ron Light Bee X"),
    ("cxorq8Rowqk_oar2.jpg",       "FRONT QUARTER",  "Lights on"),
    ("BfXaJy-ZVh4_maxres2.jpg",    "BARE FRAME",     "Powder coat over cast alloy"),
    ("ZTWO-hh79v8_oar3.jpg",       "REAR END",       "Monoshock and swingarm"),
    ("ArHl1bBvs9o_oar3.jpg",       "STANCE",         "USD forks, knobbies"),
    ("lKJifB3AJxM_oar3.jpg",       "THE PAINT",      "The reason people know it"),
    ("xk7gcHqFb8o_oar3.jpg",       "THE BAY",        "72V pack sits here"),
    ("mNnhPm2h0WY_sddefault.jpg",  "THE TRACK",      "Cut by hand"),
]

W = 1600            # output long edge
VIOLET = np.array([0.62, 0.44, 1.00])   # shadow tint direction


def grade(im):
    """Near-mono, crushed blacks, violet shadows, vignette."""
    im = im.convert("RGB")
    a = np.asarray(im).astype(np.float32) / 255.0

    # luminance, then pull most of the way to mono (keeps a whisper of the paint)
    lum = a @ np.array([0.2126, 0.7152, 0.0722], dtype=np.float32)
    a = a * 0.58 + lum[..., None] * 0.42

    # filmic-ish contrast: lift toe, crush shadows, roll highlights
    a = np.clip(a, 0, 1)
    a = np.clip((a - 0.06) / 0.90, 0, 1)
    a = a ** 1.18
    a = a * (1.0 + 0.10 * (1.0 - a))          # gentle highlight roll-off

    # violet into the shadows, cool neutral in the highlights
    shadow_w = np.clip(1.0 - lum[..., None] * 1.7, 0, 1)
    a = a + shadow_w * (VIOLET - 0.5) * 0.06
    a = np.clip(a, 0, 1)

    # vignette
    h, w = a.shape[:2]
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    cx, cy = w / 2, h / 2
    r = np.sqrt(((xx - cx) / cx) ** 2 + ((yy - cy) / cy) ** 2)
    vig = np.clip(1.0 - 0.62 * np.clip(r - 0.42, 0, None) ** 1.55, 0.06, 1.0)
    a *= vig[..., None]

    return Image.fromarray((np.clip(a, 0, 1) * 255).astype(np.uint8))


def main():
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        os.remove(os.path.join(OUT, f))

    manifest = []
    for i, (fname, label, sub) in enumerate(SHOTS):
        path = os.path.join(SRC, fname)
        if not os.path.exists(path):
            print("MISSING", fname)
            continue
        im = Image.open(path)
        if im.width >= im.height and im.width > W:
            im = im.resize((W, round(im.height * W / im.width)), Image.LANCZOS)
        elif im.height > im.width and im.height > W:
            im = im.resize((round(im.width * W / im.height), W), Image.LANCZOS)

        g = grade(im)
        name = f"h{i:02d}.jpg"
        g.save(os.path.join(OUT, name), quality=88, optimize=True, progressive=True)
        manifest.append({"src": f"assets/hero/{name}", "label": label, "sub": sub,
                         "w": g.width, "h": g.height,
                         "portrait": g.height > g.width})
        print(f"{name}  {g.width}x{g.height}  {label}")

    import json
    open(os.path.join(ROOT, "data", "hero.js"), "w").write(
        "/* AUTO-GENERATED by scripts/build_hero.py */\n"
        "export const HERO = " + json.dumps(manifest, indent=1) + ";\n")
    size = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print(f"\n{len(manifest)} shots, {size/1e6:.1f} MB")


if __name__ == "__main__":
    main()
