#!/usr/bin/env python3
"""Turn the raw scrape (videos.json / shorts.json) into data/channel.js.

Run `python3 scripts/refresh.py` to re-scrape, then this to rebuild the data file.
"""
import json, re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "data", "raw")

# Which bucket each video falls into. Anything unlisted defaults to "ride".
CATEGORY = {
    "build": [
        "Building a Yozma", "I Built My DREAM Super73", "I Built This $10,000 surron",
        "$10,000 Surron Build", "This 72V Surron Is Actually Insane",
        "Unclapping My Surron LBX", "New Ebmx 9000 controller",
    ],
    "review": [
        "VICTRIP R6", "D10 Review", "The Macfox X7", "TST R002",
        "Meet the Rixoc GT19", "ULTRA BEE", "New Surron unboxing",
        "Track Testing the GT19", "everyday things on the RIXOC",
    ],
    "howto": ["How to Wheelie", "How I Saved for a Surron"],
    "ride": ["Texas mega ride", "Lake of the Ozarks", "SECRET Dirt Bike Track"],
}


def categorize(title):
    for cat, needles in CATEGORY.items():
        for n in needles:
            if n.lower() in title.lower():
                return cat
    return "ride"


def views_num(s):
    if not s:
        return 0
    m = re.match(r"([\d.,]+)\s*([KMB]?)", s.replace(",", ""))
    if not m:
        return 0
    n = float(m.group(1))
    return int(n * {"": 1, "K": 1e3, "M": 1e6, "B": 1e9}[m.group(2)])


def main():
    videos = json.load(open(os.path.join(RAW, "videos.json")))
    shorts = json.load(open(os.path.join(RAW, "shorts.json")))

    out = []
    for v in videos:
        has_thumb = os.path.exists(os.path.join(ROOT, "assets", "thumbs", v["id"] + ".jpg"))
        out.append({
            "id": v["id"],
            "title": v["title"],
            "views": v["views"],
            "viewsNum": views_num(v["views"]),
            "published": v["published"],
            "duration": v["duration"],
            "category": categorize(v["title"]),
            "thumb": f"assets/thumbs/{v['id']}.jpg" if has_thumb
                     else f"https://i.ytimg.com/vi/{v['id']}/hqdefault.jpg",
        })

    sh = []
    for s in shorts:
        has_thumb = os.path.exists(os.path.join(ROOT, "assets", "shorts", s["id"] + ".jpg"))
        title = s.get("title") or ""
        # YouTube shows a bare date when a Short has no title — not worth displaying.
        if re.match(r"^[A-Z][a-z]+ \d{1,2}, \d{4}$", title.strip()):
            title = ""
        sh.append({
            "id": s["id"],
            "title": title,
            "views": s.get("views"),
            "viewsNum": views_num(s.get("views")),
            "thumb": f"assets/shorts/{s['id']}.jpg" if has_thumb
                     else f"https://i.ytimg.com/vi/{s['id']}/hqdefault.jpg",
        })
    sh.sort(key=lambda x: -x["viewsNum"])

    banner = "assets/brand/banner.jpg"
    js = (
        "/* AUTO-GENERATED by scripts/build_data.py — edit site copy in data/site.js instead. */\n"
        "export const VIDEOS = " + json.dumps(out, indent=2, ensure_ascii=False) + ";\n\n"
        "export const SHORTS = " + json.dumps(sh, indent=2, ensure_ascii=False) + ";\n"
    )
    path = os.path.join(ROOT, "data", "channel.js")
    open(path, "w", encoding="utf-8").write(js)
    print(f"wrote {path}: {len(out)} videos, {len(sh)} shorts")
    print("top:", max(out, key=lambda v: v["viewsNum"])["title"])
    print("banner exists:", os.path.exists(os.path.join(ROOT, banner)))


if __name__ == "__main__":
    main()
