#!/usr/bin/env python3
"""Curate the harvested frames down to a gallery of the purple Sur-Ron.

Picks the strongest violet frames, drops near-duplicates (adjacent slots of the
same video are often the same shot), and writes assets/gallery/ + a manifest.
"""
import json, os, shutil
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "frames")
OUT = os.path.join(ROOT, "assets", "gallery")
SCORES = os.path.join(ROOT, "data", "raw", "frame_scores.json")

MIN_VIOLET = 0.030      # fraction of frame that is violet paint
MAX_PER_VIDEO = 3
TARGET_W = 1100
DUPE_DIST = 12.0        # mean abs diff on a 32x18 thumb
MIN_PIXELS = 700_000    # reject the low-res slots; keeps maxres/oar only

# Violet-hue false positives: RGB keyboard lighting, a lilac dog, a skull prop.
# Reviewed by eye — add a video id here if a bad shot creeps into the gallery.
BLOCK_VIDEOS = {
    "gU6m7gxALac",   # purple keyboard backlight
    "A63s2c8Np7Q",   # dog
    "XvMvgXzSEJo",   # dog
    "qfnauJJmwUM",   # skull ornament
    "V1jVakpL7DA",   # lilac wall, no bike
}


def signature(path):
    im = Image.open(path).convert("RGB").resize((32, 18), Image.BILINEAR)
    return np.asarray(im).astype(np.float32)


def main():
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        os.remove(os.path.join(OUT, f))

    rows = [r for r in json.load(open(SCORES)) if r["violet"] >= MIN_VIOLET]
    rows.sort(key=lambda r: (-r["violet"], -r["w"]))

    picked, sigs, per_video = [], [], {}
    for r in rows:
        vid = r["file"].rsplit("_", 1)[0]
        if vid in BLOCK_VIDEOS or per_video.get(vid, 0) >= MAX_PER_VIDEO:
            continue
        path = os.path.join(SRC, r["file"])
        try:
            im0 = Image.open(path)
            if im0.width * im0.height < MIN_PIXELS:
                continue
            sig = signature(path)
        except Exception:
            continue
        if any(np.abs(sig - s).mean() < DUPE_DIST for s in sigs):
            continue
        sigs.append(sig)
        per_video[vid] = per_video.get(vid, 0) + 1
        picked.append(r)

    manifest = []
    for i, r in enumerate(picked):
        im = Image.open(os.path.join(SRC, r["file"])).convert("RGB")
        if im.width > TARGET_W:
            im = im.resize((TARGET_W, round(im.height * TARGET_W / im.width)), Image.LANCZOS)
        name = f"g{i:02d}.jpg"
        im.save(os.path.join(OUT, name), quality=86, optimize=True, progressive=True)
        manifest.append({
            "src": f"assets/gallery/{name}",
            "video": r["file"].rsplit("_", 1)[0],
            "w": im.width, "h": im.height,
            "portrait": im.height > im.width,
            "violet": r["violet"],
        })

    json.dump(manifest, open(os.path.join(ROOT, "data", "raw", "gallery.json"), "w"), indent=1)
    # Emit an ES module too, so the site works over file:// without fetch().
    open(os.path.join(ROOT, "data", "gallery.js"), "w").write(
        "/* AUTO-GENERATED by scripts/build_gallery.py */\n"
        "export const GALLERY = " + json.dumps(manifest, indent=1) + ";\n")
    size = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print(f"gallery: {len(manifest)} images, {size/1e6:.1f} MB")
    print(f"  landscape {sum(1 for m in manifest if not m['portrait'])}"
          f" / portrait {sum(1 for m in manifest if m['portrait'])}")


if __name__ == "__main__":
    main()
