#!/usr/bin/env python3
"""Build hover-preview frames for the video grid.

YouTube exposes three real in-video frames per upload (maxres1/2/3, sampled
at roughly 25/50/75% through the video). Cycling those under the pointer
gives a genuine preview of the footage — like YouTube's own hover preview,
but served from this repo with no third-party requests at runtime.

Writes assets/preview/{id}_{1..3}.jpg (480px wide) and data/preview.js.
"""
import io, json, os, re, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "preview")

from PIL import Image

def video_ids():
    src = open(os.path.join(ROOT, "data", "channel.js")).read()
    vids = json.loads(re.search(r"VIDEOS = (\[.*?\]);", src, re.S).group(1))
    return [v["id"] for v in vids]

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read()

def main():
    os.makedirs(OUT, exist_ok=True)
    manifest = {}
    for vid in video_ids():
        frames = []
        for j in (1, 2, 3):
            # maxres is best; hq falls back for older/low-res uploads
            for base in (f"maxres{j}", f"hq{j}"):
                try:
                    raw = fetch(f"https://i.ytimg.com/vi/{vid}/{base}.jpg")
                except Exception:
                    continue
                im = Image.open(io.BytesIO(raw)).convert("RGB")
                if im.width < 200:          # 120px grey placeholder = no frame
                    continue
                im = im.resize((480, round(im.height * 480 / im.width)), Image.LANCZOS)
                name = f"{vid}_{j}.jpg"
                im.save(os.path.join(OUT, name), quality=72, optimize=True)
                frames.append(f"assets/preview/{name}")
                break
        if frames:
            manifest[vid] = frames
        print(vid, len(frames), "frames")

    with open(os.path.join(ROOT, "data", "preview.js"), "w") as f:
        f.write("/* AUTO-GENERATED by scripts/build_previews.py */\n"
                "export const PREVIEW = " + json.dumps(manifest, indent=1) + ";\n")
    size = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print(f"\n{len(manifest)} videos, {size/1e6:.1f} MB")

if __name__ == "__main__":
    main()
