#!/usr/bin/env python3
"""Self-host the webfonts so the site has no third-party dependencies.

Downloads the woff2 files Google Fonts serves and rewrites the @font-face
blocks to point at assets/fonts/. Run once; re-run only to change families.
"""
import os, re, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "styles", "fonts.css")

# A modern UA is required or Google serves legacy ttf instead of woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

URL = ("https://fonts.googleapis.com/css2"
       "?family=Big+Shoulders+Display:wght@400;600;800;900"
       "&family=Barlow:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400"
       "&family=Azeret+Mono:wght@300;400;500;700"
       "&display=swap")


def get(url, ua=UA):
    req = urllib.request.Request(url, headers={"User-Agent": ua})
    return urllib.request.urlopen(req, timeout=30).read()


def main():
    os.makedirs(OUT, exist_ok=True)
    css = get(URL).decode("utf-8")

    seen = {}
    def swap(m):
        url = m.group(1)
        if url not in seen:
            name = f"f{len(seen):02d}.woff2"
            open(os.path.join(OUT, name), "wb").write(get(url))
            seen[url] = name
        return f"url(../assets/fonts/{seen[url]})"

    css = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", swap, css)
    header = ("/* AUTO-GENERATED by scripts/fetch_fonts.py — self-hosted webfonts.\n"
              "   Big Shoulders Display + Barlow + Azeret Mono, SIL Open Font License. */\n")
    open(CSS_OUT, "w", encoding="utf-8").write(header + css)

    size = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print(f"{len(seen)} font files, {size/1024:.0f} KB -> {CSS_OUT}")


if __name__ == "__main__":
    main()
